version: '3.3'
services:
  e2e-test:
    container_name: e2e-test
    build:
      context: .
      dockerfile: Dockerfile-e2e-test
    ports:
      - "4000:4000"
      - "4001:4001"
      - "5105:5105"
  spp-platform:
    image: sourceplusplus/spp-platform:latest
    container_name: spp-platform
    hostname: spp-platform
    ports:
      - "5106:5106"
      - "11800:11800"
      - "12800:12800"
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5107
      - SPP_LOGGING_LEVEL=trace
      - SW_CORE_GRPC_SSL_ENABLED=true
      - SW_CORE_GRPC_SSL_KEY_PATH=/skywalking/config/spp-platform.key
      - SW_CORE_GRPC_SSL_CERT_CHAIN_PATH=/skywalking/config/spp-platform.crt
      - SW_CORE_GRPC_SSL_TRUSTED_CA_PATH=/skywalking/config/spp-platform.crt
      - SW_RECEIVER_GRPC_SSL_ENABLED=true
      - SW_RECEIVER_GRPC_SSL_KEY_PATH=/skywalking/config/spp-platform.key
      - SW_RECEIVER_GRPC_SSL_CERT_CHAIN_PATH=/skywalking/config/spp-platform.crt
    volumes:
      - ./config/spp-platform.crt:/skywalking/config/spp-platform.crt
      - ./config/spp-platform.key:/skywalking/config/spp-platform.key
